Return topic arns when registering SNS topics
vaughanbrittonsage/eventq pull request #87
Opened 2020-06-05 13:07 UTC by ianoxley

Update the AWS `EventQClient#regiser_event` to return the topic arn of
the topic it registers.

Update the `#registered?` method too: if an event is already registered
then return its topic arn, otherwise return false.

Internally the `@known_event_types` has been changed from an array to
a hash. The existing topic key that was stored in the array is used as
the key, and the topic arn as the value.

2020-06-05 14:58 UTC, victormartins submitted a review, later dismissed
do we need release notes?

2020-06-05 17:31 UTC, rwadstein requested changes

2020-06-05 17:43 UTC, rwadstein commented
It is interesting that eventq looks to be able to support multiple topics, but not multiple queues in the worker.

2020-06-10 12:33 UTC, rwadstein submitted a review, later dismissed

2020-06-11 10:02 UTC, victormartins approved these changes

2020-06-11 11:44 UTC, chrisbarber86 commented on lib/eventq/eventq_aws/aws_eventq_client.rb
> +      # @return [String]
Since this changes the method signature this ought to be a breaking change / major version bump - i.e. tag it as v3.x.x

2020-06-11 11:44 UTC, chrisbarber86 approved these changes

2020-06-11 11:47 UTC, merged