Pcbc2 402
vaughanbrittonsage/eventq pull request #9
Opened 2017-02-08 15:57 UTC by chilts1978

2017-02-08 16:33 UTC, rwadstein commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +          EventQ.log(:info, "[#{self.class}] - options[:client] is now deprecated!!, please pass options[:mq_endpoint].")
the comment here in the log message is about `mq_endpoint` which is for rabbitmq and not aws.  But this is the aws worker.

2017-02-08 16:35 UTC, rwadstein commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +            client = options[:client] || new_client_instance(options) # singleton or non-singleton
do we really need to be backwards compatible?  This just allows a client that might not be thread safe to be introduced.
I think we should not even have this option.

2017-02-08 17:15 UTC, rwadstein requested changes

2017-02-08 17:15 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +          EventQ.log(:info, "[#{self.class}] - options[:client] is now deprecated!!, please pass options[:aws_account_no] && options[:aws_region].")
the comment here in the log message is about `aws_region` which is for aws and not rabbitmq.  But this is the rabbitmq worker.

2017-02-08 17:15 UTC, rwadstein commented on eventq_aws/lib/eventq_aws/aws_queue_manager.rb
> +          EventQ.log(:info, "[#{self.class}] - options[:client] is now deprecated!!, please pass options[:mq_endpoint].")
the comment here in the log message is about `mq_endpoint` which is for rabbitmq and not aws.  But this is the aws worker.

2017-02-08 17:15 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +            client = options[:client] || new_client_instance(options) # singleton or non-singleton
Do we need to be backwards compatible?  I think the risk outweighs the benefit of this option.

2017-02-08 17:15 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        raise "[#{self.class}] - MQ Endpoint not present." unless options[:mq_endpoint]
I don't think we need to raise here as we already will over here
https://github.com/Sage/eventq/blob/cb70cde14ec5b28119167ce0d21ad21d1defe3dd/eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_client.rb#L9

2017-02-08 17:15 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        EventQ::RabbitMq::QueueClient.new({endpoint: options[:mq_endpoint] })
this option key, `:mq_endpoint` is not used in the constructor.  You need to fix this as well
https://github.com/Sage/eventq/blob/cb70cde14ec5b28119167ce0d21ad21d1defe3dd/eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_client.rb#L9-L13

2017-02-08 17:47 UTC, chilts1978 commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +            client = options[:client] || new_client_instance(options) # singleton or non-singleton
Yes, as folks may already be consuming this gem. Its public.

2017-02-08 17:47 UTC, chilts1978 commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +        raise "[#{self.class}] - AWS Account No and Region not present." unless aws_creds_present?(options)
Belt n braces?

2017-02-08 17:48 UTC, chilts1978 commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +            client = options[:client] || new_client_instance(options) # singleton or non-singleton
Yes, in case the gem is being consumed in external apps already.

2017-02-08 17:49 UTC, chilts1978 commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        raise "[#{self.class}] - MQ Endpoint not present." unless options[:mq_endpoint]
Belt n braces?

2017-02-08 17:51 UTC, rwadstein commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +            client = options[:client] || new_client_instance(options) # singleton or non-singleton
Ok, then just put a comment here as we really don't want to support this.  And maybe a TODO to remove potentially in a major release.

2017-02-08 17:52 UTC, rwadstein commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +        raise "[#{self.class}] - AWS Account No and Region not present." unless aws_creds_present?(options)
personally, I am not a big fan of over protective software.  Plus, you raise here, but what if we make the client built upon the actual `Aws.config`, then we still raise an error here even though the client is fine.  I think it is more the responsibility of the class that needs it to raise errors.

2017-02-08 17:53 UTC, chilts1978 commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
> +        raise "[#{self.class}] - AWS Account No and Region not present." unless aws_creds_present?(options)
OK, I will remove this check. 👍

2017-02-08 17:53 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +            client = options[:client] || new_client_instance(options) # singleton or non-singleton
need comment as to why its here, but should not be used.

2017-02-08 17:53 UTC, chilts1978 commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        raise "[#{self.class}] - MQ Endpoint not present." unless options[:mq_endpoint]
I will remove 👍

2017-02-08 17:54 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        raise "[#{self.class}] - MQ Endpoint not present." unless options[:mq_endpoint]
explanation further above.

2017-02-08 18:03 UTC, chilts1978 commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        EventQ::RabbitMq::QueueClient.new({endpoint: options[:mq_endpoint] })
This is the queue client. Its a different animal. 

This is what we new up inside;

Confusing but a different set of options;

EventQ::RabbitMq::QueueClient.new({endpoint: options[:mq_endpoint] })

2017-02-08 18:08 UTC, rwadstein commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
> +        EventQ::RabbitMq::QueueClient.new({endpoint: options[:mq_endpoint] })
ahh.gotcha.  we are essentially translating key names.

2017-02-08 18:09 UTC, rwadstein approved these changes

2017-02-08 19:22 UTC, vaughanbrittonsage commented
Sorry to be picky but this has nothing to do with Sinject (The name and description of this PR is incorrect) this is to do with using a shared instance of the queue client between threads (which so far has not been an issue as the aws sdk appears to be thread safe).

2017-02-08 19:30 UTC, vaughanbrittonsage commented on eventq_rabbitmq/lib/eventq_rabbitmq/rabbitmq_queue_worker.rb
>          if options[:client] == nil
on reflection I think we should allow both singleton and instance per thread approaches and not deprecate the singleton client passed via options. As to my knowledge this has not caused us any issues? the issue that is driving this change is due to the usage of curb in an azure queue client implementation as curb is not thread safe.

2017-02-08 19:33 UTC, vaughanbrittonsage commented on eventq_aws/lib/eventq_aws/aws_queue_worker.rb
>          if options[:client] == nil
as per comment on this if statement within the rabbitmq implementation of the worker below, I suggest we modify this if statement to verify either `options[:client] == nil || options[:aws_account_no]` is specified else raise error.

2017-02-09 10:18 UTC, vaughanbrittonsage commented on eventq_aws/lib/eventq_aws/aws_queue_manager.rb
>          if options[:client] == nil
Sorry can we make this check the same as the `valid_client?(options)` check in the queue_worker?

2018-07-10 14:25 UTC, closed without merging